#!../lpp
var std=(import "iostream");
#main function start
const main=function(argc,argv){
  std.console.log ["Hello World!",std.endl];
  std.console.log ["Your name:"];
  var x=std.console.readline [];
  std.console.log ["Welcome,",x,"!",std.endl];
  std.console.log ["Now please input two numbers,use space to split",std.endl];
  var s=(std.console.readline []).split [" "];
  if (s.length!=2),{
    std.console.log ["please input TWO numbers!",std.endl];
    return 1;
  };
  var a,b;
  try {a=(int s[0]);b=(int s[1]);},catch={
    std.console.log ["number is invalid!",std.endl];
    return 1;
  };
  std.console.log ["final:",(a+b),std.endl];
  return 0;#return value
}
return (main [arguments.length,arguments]);
